http:
  routers:
    nextcloud:
      rule: Host(`cloud.dimoracosta.it`)
      entrypoints:
        - websecure
      service: nextcloud
      middlewares:
        - nextcloud-secure-headers

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: http://nextcloud-aio-apache:11000

  middlewares:
    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
          - X-Forwarded-Host
        referrerPolicy: same-origin
